feat: more flexible bisect issue comment commands
electron/bugbot pull request #100
Opened 2021-07-05 22:49 UTC by ckerr

This refactor is really to make room in the issue parser for non-bisect commands, but it has a bonus of making the bisect command more useful by letting parameters be specified in-comment and by providing sensible default values when pararameters are missing from both the commenta and the issue body.

The new syntax: `/bugbot bisect [gistId] [goodVersion [badVersion]]`

- If no `gistId` is given, the `Testcase Gist URL` header is used.
- If no `goodVersion` is given, an older Electron version is used.
- If no `badVersion` is given, the `Electron Version` header is used.
  If that's missing too, the latest release is used.

This is all explained now at the top of the README.md so that we can link to it / so that it will be easier for maintainers to find.

2021-07-05 22:55 UTC, ckerr commented on modules/bot/test/fixtures/issue-gist-trailing-slash.md
> +12.0.0
Side comment: fixed wart in the issue-parser test + fixtures that specified the good release to be newer than the bad release

2021-07-08 22:46 UTC, clavin requested changes

2021-07-08 22:46 UTC, clavin commented on modules/bot/src/github-client.ts
> +
Is this meant to be left here? In the middle of the class? If so, what is this a draft implementation *of*?

2021-07-08 22:46 UTC, clavin commented on modules/bot/src/issue-parser.ts
> +  if (input?.startsWith('https://gist.github.com/')) {
The type `string` can't be `null` or `undefined` though?

2021-07-08 22:46 UTC, clavin commented on modules/bot/src/issue-parser.ts
> +  goodVersion ||= await versions.getDefaultBisectStart();
long nit:

I think `version ??= ... ?? ...;` may be more clear than `version ||= ...; version ||= ...;`

Alternatively, name the two previous variables `argBadVersion` and `argGoodVersion`, make their types `string | undefined`, and then make these two statements sort of like this:

```ts
const badVersion = argBadVersion ?? ... ?? ...;
// (and then again for goodVersion)
```

2021-07-08 22:46 UTC, clavin commented on modules/bot/src/issue-parser.ts
> +const allPlatforms = ['darwin', 'linux', 'win32'];
```suggestion
const ALL_PLATFORMS = ['darwin', 'linux', 'win32'];
```

2021-07-08 22:56 UTC, erickzhao commented on modules/bot/src/github-client.ts
> +
It's out of scope for this PR, but this draft implementation was originally added in #24 but we removed it to focus on the `/test bisect` command.

2021-07-08 23:24 UTC, erickzhao reviewed
Leaving a review right now just for the docs changes

2021-07-08 23:24 UTC, erickzhao commented on README.md
> +### by Bug Reporters
```suggestion
### By bug reporters
```

2021-07-08 23:24 UTC, erickzhao commented on README.md
> +### by Maintainers
```suggestion
### By maintainers
```

2021-07-08 23:24 UTC, erickzhao commented on README.md
> +1. Users [file Electron bug reports](https://github.com/electron/electron/issues/new/choose) with [tests](#for-bug-reporters).
```suggestion
1. Users [file Electron bug reports](https://github.com/electron/electron/issues/new/choose) with [tests](#by-bug-reporters).
```

2021-07-08 23:24 UTC, erickzhao commented on README.md
> +If you want to do it manually, the only requirement is that 0/1 `exitCode`. You can write it from scratch or use [electron-quickstart](https://github.com/electron/electron-quickstart)'s [`test-templa
```suggestion
If you want to do it manually, the only requirement is that 0/1 `exitCode`. You can write it from scratch or use [electron-quick-start](https://github.com/electron/electron-quick-start)'s [`test-template` branch](https://github.com/electron/electron-quick-start/tree/test-template) as a starting point, which is the same template used by Electron Fiddle. You can clone it from the command line with `git clone --branch test-template https://github.com/electron/electron-quick-start`, then use a web browser to upload it to [gist.github.com](https://gist.github.com/).
```

2021-07-08 23:24 UTC, erickzhao commented on README.md
> +- If no `platforms` are given, test on Linux, Mac, and Windows.
```suggestion
- If no `platforms` are given, test on Linux, macOS, and Windows.
```

2021-07-08 23:24 UTC, erickzhao commented on README.md
> +- If no `versions` are given, test the first version and latest version of each prerelease branch, of each supported branch, and of the two branches before that.
We can link the supported branch docs here

2021-07-08 23:24 UTC, erickzhao commented on README.md
> +## tldr
```suggestion
## Overview
```

2021-07-09 03:13 UTC, ckerr commented on README.md
> +- If no `versions` are given, test the first version and latest version of each prerelease branch, of each supported branch, and of the two branches before that.
Added cb3f7fac58ab52a3bada34c0df2854914e6ea26c

2021-07-09 03:22 UTC, ckerr commented on modules/bot/src/issue-parser.ts
> +  if (input?.startsWith('https://gist.github.com/')) {
Actually looks like we were passing in `undefined` below in `ret.gistId = getGistId(sections.get(TESTCASE_URL));` ... I'll fix the method signature to match how it's being used.

2021-07-09 03:29 UTC, ckerr commented on modules/bot/src/issue-parser.ts
> +  if (input?.startsWith('https://gist.github.com/')) {
Updated in d63527a5b1ee6d85e926d9fb20a4f4619697b57b

2021-07-09 03:30 UTC, ckerr commented on modules/bot/src/issue-parser.ts
> +  goodVersion ||= await versions.getDefaultBisectStart();
> I think version ??= ... ?? ...; may be more clear than version ||= ...; version ||= ...;

No, I don't think that's right. `??=` implies we want to keep a falsy string, e.g. a version of `''`, when we really don't.

You're right though that it's strange to be allowing `undefined` for these variables without making it explicit in the types though.  I've updated that in 862aad5

2021-07-09 23:38 UTC, clavin requested changes

2021-07-09 23:38 UTC, clavin commented on modules/bot/src/issue-parser.ts
> +  if (input?.startsWith('https://gist.github.com/')) {
I still think that this function signature doesn't exactly make sense, like when would someone ever call `getGistId()` specifically with no input (or specifically with `undefined`/`null`)? Sort of a nit, but I rather modify the call site in this case to make the signature make more sense.

2021-07-09 23:38 UTC, clavin commented on modules/bot/src/issue-parser.ts
> +  goodVersion ||= await versions.getDefaultBisectStart();
Oh I didn't even think about `''` not being retained in this version of the code, it's just not very clear that is the intention imo.

Another thought: this code *always* evaluates the `await versions.getXyz()` and waits for it, even when it doesn't need to. I think a restructure here would be good for clarity and doing a little less work when we don't need to.

2021-07-09 23:53 UTC, ckerr commented on modules/bot/src/issue-parser.ts
> +  if (input?.startsWith('https://gist.github.com/')) {
`getGistId()` is literally called with no input / undefined / null in the code I quoted above. It passes in whatever `Map<string, string>.get(TESTCASE_URL)` has and lets the function sort it out.

2021-07-09 23:56 UTC, ckerr commented on modules/bot/src/issue-parser.ts
> +  goodVersion ||= await versions.getDefaultBisectStart();
That's incorrect. When `version` is truthy, the right-hand side of `||=` is not evaluated.

2021-07-12 16:38 UTC, clavin commented on modules/bot/src/issue-parser.ts
> +  goodVersion ||= await versions.getDefaultBisectStart();
Ah you're right, short-circuiting does work with `||=`, I just did not expect it to. Fair enough!

2021-07-12 16:41 UTC, clavin commented on modules/bot/src/issue-parser.ts
> +  if (input?.startsWith('https://gist.github.com/')) {
I guess I'm still hazy about the details of how "get gist id of [nothing]" makes sense, i.e. why the handling of undefined is the responsibility of this function, but this is a non-blocker so I'm more than willing to gloss over it.

2021-07-12 16:42 UTC, clavin approved these changes
My remaining comments aren't blockers 👍

2021-07-12 16:53 UTC, merged