feat: have runner bisect w/obsolete, beta, nightly
electron/bugbot pull request #108
Opened 2021-07-06 17:01 UTC by ckerr

When running `electron-fiddle bisect`, include arguments to pull in all of the Electron releases so that the bisection range will be as small as possible.

Fixes #66 as a side-effect.

2021-07-06 17:07 UTC, ckerr commented on modules/runner/src/runner.ts
> +        ...['bisect', range[0], range[1]],
_(style nit)_ I'd like a second opinion on this. The goal is to make explicit that these arguments must all be grouped together. If not for prettier, I'd do  something like

```js
  ...fiddleArg,
  'bisect', range[0], range[1],
  '--betas',
  '--fiddle', gistId,
  '--nightlies',
  '--obsolete',
``` 

...but that indentation gets "fixed" by prettier. So I did this instead, but am undecided if this is an improvement because it looks a little weird.

2021-07-08 20:04 UTC, clavin requested changes

2021-07-08 20:04 UTC, clavin commented on modules/runner/src/runner.ts
> +        ...['bisect', range[0], range[1]],
I know I'm late now, but since the `--all` PR has been merged and pending release very soon, can this be updated to use it?

2021-07-08 20:37 UTC, ckerr commented on modules/runner/src/runner.ts
> +        ...['bisect', range[0], range[1]],
Good call.

2021-07-08 20:49 UTC, ckerr commented on modules/runner/src/runner.ts
> +        ...['bisect', range[0], range[1]],
Added in 86648027a216b5cecdc45dcc9e680136544c3063

2021-07-08 22:09 UTC, clavin approved these changes

2021-07-08 22:23 UTC, merged