feat: support + validate new test tasks in broker
electron/bugbot pull request #112
Opened 2021-07-07 21:16 UTC by ckerr

Replaces some very bad broker validation code (of mine) with some new ow predicates. This includes a TestJob predicate so the broker now supports both Test and Bisect tasks.

Fixes #110.

2021-07-08 23:18 UTC, clavin requested changes

2021-07-08 23:18 UTC, clavin commented on modules/broker/src/server.ts
> +      const scratch = JSON.parse(JSON.stringify(task.job)); // deep copy
nit: I would prefer adding a dependency for deep copying instead of this

2021-07-08 23:18 UTC, clavin commented on modules/broker/src/task.ts
> +    assertJob(job);
I think the constructor should take `job: Job` and it should be the caller's responsibility to ensure that a job is passed into the constructor here.

2021-07-08 23:41 UTC, ckerr commented on modules/broker/src/server.ts
> +      const scratch = JSON.parse(JSON.stringify(task.job)); // deep copy
At first look, Klona looks like it might be good. 0 dependencies and lots of users.

Any opinions?

2021-07-09 03:42 UTC, ckerr commented on modules/broker/src/server.ts
> +      const scratch = JSON.parse(JSON.stringify(task.job)); // deep copy
I went with Klona. 01e8d569229be

2021-07-09 03:42 UTC, ckerr commented on modules/broker/src/task.ts
> +    assertJob(job);
Oh yeah, that is better! I think I had it as `unknown` as part of an incomplete change.

Fixed in c6f0b044193316

2021-07-09 23:29 UTC, clavin approved these changes

2021-07-10 00:02 UTC, merged