feat(broker): add PORT as env variable fallback
electron/bugbot pull request #61
Opened 2021-06-15 22:25 UTC by erickzhao

In preparation for deploying the broker to Heroku, this PR adds a `$PORT` environment variable fallback for the express server.

Each Heroku web process must bind to a port specified by the `$PORT` environment variable, which is assigned by Heroku itself when a dyno is spun up. See Heroku's [Runtime Principles](https://devcenter.heroku.com/articles/runtime-principles#web-servers) doc for more information.

2021-06-15 22:30 UTC, clavin approved these changes
👍

2021-06-15 22:33 UTC, clavin requested changes
Just thought of an edge case after my last review

2021-06-15 22:33 UTC, clavin commented on modules/broker/src/server.ts
> +    this.port = Number.parseInt(this.brokerUrl.port, 10) || envInt('PORT');
Could we assign `this.brokerUrl.port = this.port` somehow so we don't end up with an edge case where the broker is using URLs of itself with the wrong/a missing port?

2021-06-16 01:27 UTC, clavin approved these changes

2021-06-16 15:08 UTC, ckerr approved these changes
The code looks fine. This is a clean way of doing it. URL.port is a string anyway so no conversion is necessary.

I'm kind of curious if heroku config vars can refer to other config vars, e.g. could we do this 
 by setting `BUGBOT_BROKER_URL` to `https://bugbot.electronjs.org:$PORT" instead of adding Heroku-specific code. If that doesn't work, I'm :+1: with the approach in this PR

We might want to document this in the env variables section of the README.md

2021-06-16 16:54 UTC, merged